server:
  port: 0

spring:
  application:
    name: news-msvc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/fixed_assets
    username: postgres
    password: stefannloaiza
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka