server:
  port: 8080

spring:
  application:
    name: gateway-msvc
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: assets-msvc
          uri: lb://assets-msvc
          predicates:
            - Path=/api/v1/assets/**

        - id: users-msvc
          uri: lb://users-msvc
          predicates:
            - Path=/api/v1/users/**

        - id: assignment-msvc
          uri: lb://assignment-msvc
          predicates:
            - Path=/api/v1/assignment/**

        - id: maintenance-msvc
          uri: lb://maintenance-msvc
          predicates:
            - Path=/api/v1/maintenance/**

        - id: depreciation-msvc
          uri: lb://depreciation-msvc
          predicates:
            - Path=/api/v1/depreciation/**

        - id: news-msvc
          uri: lb://news-msvc
          predicates:
            - Path=/api/v1/news/**

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG