server:
  port: 8083

spring:
  application:
    name: assignment-msvc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/fixed_assets
    username: postgres
    password: stefannloaiza
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql