server:
  port: 8761

spring:
  application:
    name: eureka-discovery-server

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false

  client:
    registerWithEureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/