server:
  port: 8080

spring:
  application:
    name: assets-msvc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/fixed_assets
    username: postgres
    password: stefannloaiza
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql